
let iota = 0;

// REGISTER INDEXES
const REG_A   = 0;
const REG_B   = 1;
const REG_C   = 2;
const REG_D   = 3;
const REG_E   = 4;
const REG_H   = 5;
const REG_L   = 6;
const REG_SPH = 7;
const REG_SPL = 8;
const REG_SP  = REG_SPH;
const REG_PCH = 9;
const REG_PCL = 10;
const REG_PC  = REG_PCH;

// FLAG INDEXES
const FLAG_S  = 0;
const FLAG_Z  = 1;
const FLAG_AC = 2;
const FLAG_P  = 3;
const FLAG_CY = 4;

// FLAG MASKS
const FLAG_S_MASK  = (1 << 7);
const FLAG_Z_MASK  = (1 << 6);
const FLAG_AC_MASK = (1 << 4);
const FLAG_P_MASK  = (1 << 2);
const FLAG_CY_MASK = (1 << 0);

// REGISTER CODES
const REG_A_CODE = 0b111;
const REG_B_CODE = 0b000;
const REG_C_CODE = 0b001;
const REG_D_CODE = 0b010;
const REG_M_CODE = 0b110;
const REG_E_CODE = 0b011;
const REG_H_CODE = 0b100;
const REG_L_CODE = 0b101;

const RP_BC_CODE = 0b00;
const RP_DE_CODE = 0b01;
const RP_HL_CODE = 0b10;
const RP_SP_CODE = 0b11;

const REG_CODE_TO_IDX = [
    REG_B, REG_C, REG_D, REG_E, REG_H, REG_L, 0b000, REG_A
];

const REG_IDX_TO_CODE = [
    REG_A_CODE, REG_B_CODE, REG_C_CODE, REG_D_CODE,
    REG_E_CODE, REG_H_CODE, REG_L_CODE
];

const RP_CODE_TO_IDX = [
    REG_B, REG_D, REG_H, REG_SP
];

// ENUMS
const INSTR_TY_ADD = iota++;
const INSTR_TY_SUB = iota++;

const MSG_TY_DFLT = iota++;
const MSG_TY_EXEC = iota++;


// CONSTANTS

const TOKEN_NONE      = iota++;
const TOKEN_MNEMONIC  = iota++;
const TOKEN_NUMBER    = iota++;
const TOKEN_REGISTER  = iota++;
const TOKEN_LABEL_DEF = iota++;
const TOKEN_LABEL_USE = iota++;
const TOKEN_DIRECTIVE = iota++;
const TOKEN_COMMA     = iota++;

const DIRECTIVE_ORG = iota++;
const DIRECTIVE_DB  = iota++;

const INSTR_NOP      = 0x00; // Done
const INSTR_LXI_B    = 0x01; // Done
const INSTR_STAX_B   = 0x02; // Done
const INSTR_INX_B    = 0x03; // Done
const INSTR_INR_B    = 0x04; // Done
const INSTR_DCR_B    = 0x05; // Done
const INSTR_MVI_B    = 0x06; // Done
const INSTR_RLC      = 0x07; // Done
const INSTR_DAD_B    = 0x09; // Done
const INSTR_LDAX_B   = 0x0A; // Done
const INSTR_DCX_B    = 0x0B; // Done
const INSTR_INR_C    = 0x0C; // Done
const INSTR_DCR_C    = 0x0D; // Done
const INSTR_MVI_C    = 0x0E; // Done
const INSTR_RRC      = 0x0F; // Done
const INSTR_LXI_D    = 0x11; // Done
const INSTR_STAX_D   = 0x12; // Done
const INSTR_INX_D    = 0x13; // Done
const INSTR_INR_D    = 0x14; // Done
const INSTR_DCR_D    = 0x15; // Done
const INSTR_MVI_D    = 0x16; // Done
const INSTR_RAL      = 0x17; // Done
const INSTR_DAD_D    = 0x19; // Done
const INSTR_LDAX_D   = 0x1A; // Done
const INSTR_DCX_D    = 0x1B; // Done
const INSTR_INR_E    = 0x1C; // Done
const INSTR_DCR_E    = 0x1D; // Done
const INSTR_MVI_E    = 0x1E; // Done
const INSTR_RAR      = 0x1F; // Done
const INSTR_RIM      = 0x20;
const INSTR_LXI_H    = 0x21; // Done
const INSTR_SHLD     = 0x22; // Done
const INSTR_INX_H    = 0x23; // Done
const INSTR_INR_H    = 0x24; // Done
const INSTR_DCR_H    = 0x25; // Done
const INSTR_MVI_H    = 0x26; // Done
const INSTR_DAA      = 0x27; // Done
const INSTR_DAD_H    = 0x29; // Done
const INSTR_LHLD     = 0x2A; // Done
const INSTR_DCX_H    = 0x2B; // Done
const INSTR_INR_L    = 0x2C; // Done
const INSTR_DCR_L    = 0x2D; // Done
const INSTR_MVI_L    = 0x2E; // Done
const INSTR_CMA      = 0x2F; // Done
const INSTR_SIM      = 0x30; 
const INSTR_LXI_SP   = 0x31; // Done
const INSTR_STA      = 0x32; // Done
const INSTR_INX_SP   = 0x33; // Done
const INSTR_INR_M    = 0x34; // Done
const INSTR_DCR_M    = 0x35; // Done
const INSTR_MVI_M    = 0x36; // Done
const INSTR_STC      = 0x37; // Done
const INSTR_DAD_SP   = 0x39; // Done
const INSTR_LDA      = 0x3A; // Done
const INSTR_DCX_SP   = 0x3B; // Done
const INSTR_INR_A    = 0x3C; // Done
const INSTR_DCR_A    = 0x3D; // Done
const INSTR_MVI_A    = 0x3E; // Done
const INSTR_CMC      = 0x3F; // Done
const INSTR_MOV_B_B  = 0x40; // Done
const INSTR_MOV_B_C  = 0x41; // Done
const INSTR_MOV_B_D  = 0x42; // Done
const INSTR_MOV_B_E  = 0x43; // Done
const INSTR_MOV_B_H  = 0x44; // Done
const INSTR_MOV_B_L  = 0x45; // Done
const INSTR_MOV_B_M  = 0x46; // Done
const INSTR_MOV_B_A  = 0x47; // Done
const INSTR_MOV_C_B  = 0x48; // Done
const INSTR_MOV_C_C  = 0x49; // Done
const INSTR_MOV_C_D  = 0x4A; // Done
const INSTR_MOV_C_E  = 0x4B; // Done
const INSTR_MOV_C_H  = 0x4C; // Done
const INSTR_MOV_C_L  = 0x4D; // Done
const INSTR_MOV_C_M  = 0x4E; // Done
const INSTR_MOV_C_A  = 0x4F; // Done
const INSTR_MOV_D_B  = 0x50; // Done
const INSTR_MOV_D_C  = 0x51; // Done
const INSTR_MOV_D_D  = 0x52; // Done
const INSTR_MOV_D_E  = 0x53; // Done
const INSTR_MOV_D_H  = 0x54; // Done
const INSTR_MOV_D_L  = 0x55; // Done
const INSTR_MOV_D_M  = 0x56; // Done
const INSTR_MOV_D_A  = 0x57; // Done
const INSTR_MOV_E_B  = 0x58; // Done
const INSTR_MOV_E_C  = 0x59; // Done
const INSTR_MOV_E_D  = 0x5A; // Done
const INSTR_MOV_E_E  = 0x5B; // Done
const INSTR_MOV_E_H  = 0x5C; // Done
const INSTR_MOV_E_L  = 0x5D; // Done
const INSTR_MOV_E_M  = 0x5E; // Done
const INSTR_MOV_E_A  = 0x5F; // Done
const INSTR_MOV_H_B  = 0x60; // Done
const INSTR_MOV_H_C  = 0x61; // Done
const INSTR_MOV_H_D  = 0x62; // Done
const INSTR_MOV_H_E  = 0x63; // Done
const INSTR_MOV_H_H  = 0x64; // Done
const INSTR_MOV_H_L  = 0x65; // Done
const INSTR_MOV_H_M  = 0x66; // Done
const INSTR_MOV_H_A  = 0x67; // Done
const INSTR_MOV_L_B  = 0x68; // Done
const INSTR_MOV_L_C  = 0x69; // Done
const INSTR_MOV_L_D  = 0x6A; // Done
const INSTR_MOV_L_E  = 0x6B; // Done
const INSTR_MOV_L_H  = 0x6C; // Done
const INSTR_MOV_L_L  = 0x6D; // Done
const INSTR_MOV_L_M  = 0x6E; // Done
const INSTR_MOV_L_A  = 0x6F; // Done
const INSTR_MOV_M_B  = 0x70; // Done
const INSTR_MOV_M_C  = 0x71; // Done
const INSTR_MOV_M_D  = 0x72; // Done
const INSTR_MOV_M_E  = 0x73; // Done
const INSTR_MOV_M_H  = 0x74; // Done
const INSTR_MOV_M_L  = 0x75; // Done
const INSTR_HLT      = 0x76; // Done
const INSTR_MOV_M_A  = 0x77; // Done
const INSTR_MOV_A_B  = 0x78; // Done
const INSTR_MOV_A_C  = 0x79; // Done
const INSTR_MOV_A_D  = 0x7A; // Done
const INSTR_MOV_A_E  = 0x7B; // Done
const INSTR_MOV_A_H  = 0x7C; // Done
const INSTR_MOV_A_L  = 0x7D; // Done
const INSTR_MOV_A_M  = 0x7E; // Done
const INSTR_MOV_A_A  = 0x7F; // Done
const INSTR_ADD_B    = 0x80; // Done
const INSTR_ADD_C    = 0x81; // Done
const INSTR_ADD_D    = 0x82; // Done
const INSTR_ADD_E    = 0x83; // Done
const INSTR_ADD_H    = 0x84; // Done
const INSTR_ADD_L    = 0x85; // Done
const INSTR_ADD_M    = 0x86; // Done
const INSTR_ADD_A    = 0x87; // Done
const INSTR_ADC_B    = 0x88; // Done
const INSTR_ADC_C    = 0x89; // Done
const INSTR_ADC_D    = 0x8A; // Done
const INSTR_ADC_E    = 0x8B; // Done
const INSTR_ADC_H    = 0x8C; // Done
const INSTR_ADC_L    = 0x8D; // Done
const INSTR_ADC_M    = 0x8E; // Done
const INSTR_ADC_A    = 0x8F; // Done
const INSTR_SUB_B    = 0x90; // Done
const INSTR_SUB_C    = 0x91; // Done
const INSTR_SUB_D    = 0x92; // Done
const INSTR_SUB_E    = 0x93; // Done
const INSTR_SUB_H    = 0x94; // Done
const INSTR_SUB_L    = 0x95; // Done
const INSTR_SUB_M    = 0x96; // Done
const INSTR_SUB_A    = 0x97; // Done
const INSTR_SBB_B    = 0x98; // Done
const INSTR_SBB_C    = 0x99; // Done
const INSTR_SBB_D    = 0x9A; // Done
const INSTR_SBB_E    = 0x9B; // Done
const INSTR_SBB_H    = 0x9C; // Done
const INSTR_SBB_L    = 0x9D; // Done
const INSTR_SBB_M    = 0x9E; // Done
const INSTR_SBB_A    = 0x9F; // Done
const INSTR_ANA_B    = 0xA0; // Done
const INSTR_ANA_C    = 0xA1; // Done
const INSTR_ANA_D    = 0xA2; // Done
const INSTR_ANA_E    = 0xA3; // Done
const INSTR_ANA_H    = 0xA4; // Done
const INSTR_ANA_L    = 0xA5; // Done
const INSTR_ANA_M    = 0xA6; // Done
const INSTR_ANA_A    = 0xA7; // Done
const INSTR_XRA_B    = 0xA8; // Done
const INSTR_XRA_C    = 0xA9; // Done
const INSTR_XRA_D    = 0xAA; // Done
const INSTR_XRA_E    = 0xAB; // Done
const INSTR_XRA_H    = 0xAC; // Done
const INSTR_XRA_L    = 0xAD; // Done
const INSTR_XRA_M    = 0xAE; // Done
const INSTR_XRA_A    = 0xAF; // Done
const INSTR_ORA_B    = 0xB0; // Done
const INSTR_ORA_C    = 0xB1; // Done
const INSTR_ORA_D    = 0xB2; // Done
const INSTR_ORA_E    = 0xB3; // Done
const INSTR_ORA_H    = 0xB4; // Done
const INSTR_ORA_L    = 0xB5; // Done
const INSTR_ORA_M    = 0xB6; // Done
const INSTR_ORA_A    = 0xB7; // Done
const INSTR_CMP_B    = 0xB8; // Done
const INSTR_CMP_C    = 0xB9; // Done
const INSTR_CMP_D    = 0xBA; // Done
const INSTR_CMP_E    = 0xBB; // Done
const INSTR_CMP_H    = 0xBC; // Done
const INSTR_CMP_L    = 0xBD; // Done
const INSTR_CMP_M    = 0xBE; // Done
const INSTR_CMP_A    = 0xBF; // Done
const INSTR_RNZ      = 0xC0; // Done
const INSTR_POP_B    = 0xC1; // Done
const INSTR_JNZ      = 0xC2; // Done
const INSTR_JMP      = 0xC3; // Done
const INSTR_CNZ      = 0xC4; // Done
const INSTR_PUSH_B   = 0xC5; // Done
const INSTR_ADI      = 0xC6; // Done
const INSTR_RST_0    = 0xC7; // Done
const INSTR_RZ       = 0xC8; // Done
const INSTR_RET      = 0xC9; // Done
const INSTR_JZ       = 0xCA; // Done
const INSTR_CZ       = 0xCC; // Done
const INSTR_CALL     = 0xCD; // Done
const INSTR_ACI      = 0xCE; // Done
const INSTR_RST_1    = 0xCF; // Done
const INSTR_RNC      = 0xD0; // Done
const INSTR_POP_D    = 0xD1; // Done
const INSTR_JNC      = 0xD2; // Done
const INSTR_OUT      = 0xD3;
const INSTR_CNC      = 0xD4; // Done
const INSTR_PUSH_D   = 0xD5; // Done
const INSTR_SUI      = 0xD6; // Done
const INSTR_RST_2    = 0xD7; // Done
const INSTR_RC       = 0xD8; // Done
const INSTR_JC       = 0xDA; // Done
const INSTR_IN       = 0xDB;
const INSTR_CC       = 0xDC; // Done
const INSTR_SBI      = 0xDE; // Done
const INSTR_RST_3    = 0xDF; // Done
const INSTR_RPO      = 0xE0; // Done
const INSTR_POP_H    = 0xE1; // Done
const INSTR_JPO      = 0xE2; // Done
const INSTR_XTHL     = 0xE3; // Done
const INSTR_CPO      = 0xE4; // Done
const INSTR_PUSH_H   = 0xE5; // Done
const INSTR_ANI      = 0xE6; // Done
const INSTR_RST_4    = 0xE7; // Done
const INSTR_RPE      = 0xE8; // Done
const INSTR_PCHL     = 0xE9; // Done
const INSTR_JPE      = 0xEA; // Done
const INSTR_XCHG     = 0xEB; // Done
const INSTR_CPE      = 0xEC; // Done
const INSTR_XRI      = 0xEE; // Done
const INSTR_RST_5    = 0xEF; // Done
const INSTR_RP       = 0xF0; // Done
const INSTR_POP_PSW  = 0xF1; // Done
const INSTR_JP       = 0xF2; // Done
const INSTR_DI       = 0xF3;
const INSTR_CP       = 0xF4; // Done
const INSTR_PUSH_PSW = 0xF5; // Done
const INSTR_ORI      = 0xF6; // Done
const INSTR_RST_6    = 0xF7; // Done
const INSTR_RM       = 0xF8; // Done
const INSTR_SPHL     = 0xF9; // Done
const INSTR_JM       = 0xFA; // Done
const INSTR_EI       = 0xFB;
const INSTR_CM       = 0xFC; // Done
const INSTR_CPI      = 0xFE; // Done
const INSTR_RST_7    = 0xFF; // Done

const MEMORY_SIZE = 65536;
